# Stage 2: Building your PostgreSQL environment
FROM python:3.11.1-slim-buster as postgres-env
WORKDIR /app
COPY --from=git /project .
COPY --from=git /project/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set environment variables
ENV DEBIAN_FRONTEND="noninteractive"
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=test_db

# Install PostgreSQL
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib && \
    rm -rf /var/lib/apt/lists/*

# Log the contents of /usr/local/bin to ensure the entrypoint script is there
RUN ls -la /usr/local/bin/

# Log the contents of the root directory
RUN ls -la /

# Set the entrypoint script as the entrypoint
CMD ["/usr/local/bin/entrypoint.sh"]

# Expose the default PostgreSQL port
EXPOSE 5432