# Use the official PostgreSQL image from Docker Hub
FROM postgres

# Environment variables
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=test_db
ENV POSTGRES_INITDB_ARGS="--wal-level=logical"

# Expose port 5432 to connect to the database
EXPOSE 5432