# Use the official pgAdmin image from the Docker library
FROM dpage/pgadmin4:latest

# Set environment variables
ENV PGADMIN_DEFAULT_EMAIL=root@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=root
ENV PGADMIN_DEFAULT_DB=test_db
ENV PGADMIN_DEFAULT_SERVER=postgres

# Expose port 80 on which pgAdmin runs
EXPOSE 80