# Use the official pgAdmin image from Docker Hub
FROM dpage/pgadmin4

# Environment variables
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=root

# Expose port 5050
EXPOSE 5050