name: Pgadmin UI
language: nodejs
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic to write data to
    defaultValue: output-topic
    required: true
dockerfile: dockerfile
defaultFile: main.js
