name: Ingest to Upstash VectorDB
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic for demo data
    defaultValue: embeddings-sbert-v1
    required: true
  - name: vectordbname
    inputType: FreeText
    description: ''
    defaultValue: quix-demo
    required: true
  - name: collectionname
    inputType: FreeText
    description: ''
    defaultValue: books-catalog
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
