name: Ingest to Upstash VectorDB
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic for demo data
    defaultValue: embeddings-sbert-v1
    required: true
  - name: upstash_vectordb_token
    inputType: Secret
    description: ''
    defaultValue: upstash_vectordb_token
    required: true
  - name: upstash_vectordb_endpoint
    inputType: FreeText
    description: ''
    defaultValue: https://active-arachnid-42631-eu1-vector.upstash.io
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
