name: qd_writer
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: transform
    required: false
  - name: pg_user
    inputType: FreeText
    description: The db username
    defaultValue: root
    required: true
  - name: pg_pwd
    inputType: FreeText
    description: The db password
    defaultValue: root
    required: true
  - name: pg_host
    inputType: FreeText
    description: The db host
    defaultValue: 'postgres'
    required: true
  - name: pg_port
    inputType: FreeText
    description: The db port
    defaultValue: '5432'
    required: true
  - name: pg_database
    inputType: FreeText
    description: The db name
    defaultValue: 'test_db'
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
